# OBJECTS = main.o Event.o State.o CSV.o
# EVENT = src/Event.cpp
# STATE = src/State.cpp
# CSV = src/CSV.cpp

# all: Simulation

# #Linking Rules
# Simulation: $(OBJECTS)
# 	g++ -g -o Simulation $(OBJECTS)

# #Compiling Rules
# main.o: main.cpp
# 	g++ -Wall -g -o main.o main.cpp

# Event.o: $(EVENT)
# 	g++ -Wall -g -o Event.o $(EVENT)

# State.o: $(STATE)
# 	g++ -Wall -g -o State.o $(STATE)

# CSV.o: $(CSV)
# 	g++ -Wall -g -o CSV.o $(CSV)

# clean:
# 	rm -f Simulation $(OBJECTS)

all:
	g++ -g  .\main.cpp .\src\Event.cpp .\src\State.cpp .\src\CSV.cpp -o simulation